version: '3'
services:
  app:
    build: ./app
    command: [ "uvicorn", "main:app", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:admin@db/sentiment
      - MODEL_FILE_PATH=/app/ai_model/model/roberta_sentiment
    restart: always  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'sentiment'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:  

      
