# Use the official MySQL image as the base image
FROM mysql:8.0

# Environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_DATABASE=sentiment

# Specify the volume for persistent data
VOLUME /var/lib/mysql
